In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [91]:
from google.colab import files
data = files.upload()

Saving kaggle_-1000.csv to kaggle_-1000 (2).csv


In [92]:
data

{'kaggle_-1000 (2).csv': b',title,uploaded_by,last_updated,usability,files,size,upvotes,badge\n0,COVID-19 Open Research Dataset Challenge (CORD-19),Allen Institute For AI , Updated 12 days ago,8.8," 558167 Files (JSON, CSV, other) ", 14 GB,9710,Gold\n1,Animal Crossing New Horizons Catalog,Jessica Li , Updated 7 months ago,8.2, 30 Files (CSV) , 591 kB,9652,Gold\n2,Credit Card Fraud Detection,Machine Learning Group - ULB , Updated 4 years ago,8.5, 1 File (CSV) , 69 MB,8712,Gold\n3,Netflix Movies and TV Shows,Shivam Bansal , Updated 3 months ago,10.0, 1 File (CSV) , 1 MB,6056,Gold\n4,Novel Corona Virus 2019 Dataset,SRK , Updated 6 months ago,9.7, 6 Files (CSV) , 9 MB,5679,Gold\n5,Heart Disease UCI,ronit , Updated 4 years ago,7.6, 1 File (CSV) , 3 kB,5538,Gold\n6,Chest X-Ray Images (Pneumonia),Paul Mooney , Updated 4 years ago,7.5, 5856 Files (other) , 2 GB,4637,Gold\n7,Trending YouTube Video Statistics,Mitchell J , Updated 3 years ago,7.9," 20 Files (CSV, JSON) ", 211 MB,4365,Gold\n8,Vide

In [93]:
df = pd.read_csv('kaggle_-1000 (2).csv')

In [94]:
df

Unnamed: 0                                              title  \
0             0  COVID-19 Open Research Dataset Challenge (CORD...   
1             1               Animal Crossing New Horizons Catalog   
2             2                        Credit Card Fraud Detection   
3             3                        Netflix Movies and TV Shows   
4             4                    Novel Corona Virus 2019 Dataset   
..          ...                                                ...   
994         994                      Economic Freedom of the World   
995         995                    Zillow Rent Index, 2010-Present   
996         996                   The Interview Attendance Problem   
997         997                          US Population By Zip Code   
998         998                           British Birdsong Dataset   

                       uploaded_by           last_updated  usability  \
0          Allen Institute For AI     Updated 12 days ago        8.8   
1                      Jessica Li    Updated 7 months ago        8.2   
2    Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                   Shivam Bansal    Updated 3 months ago       10.0   
4                             SRK    Updated 6 months ago        9.7   
..                             ...                    ...        ...   
994  Guillermina Sutter Schneider     Updated 3 years ago        7.4   
995                        Zillow     Updated 5 years ago        7.4   
996                VishnuRaghavan     Updated 4 years ago        7.9   
997              US Census Bureau     Updated 5 years ago        8.2   
998                Rachael Tatman     Updated 4 years ago        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 9 columns]

# Drop Entire Column (Unnamed: 0)

In [95]:
df = df.drop(['Unnamed: 0'],axis = 1)
df

title  \
0    COVID-19 Open Research Dataset Challenge (CORD...   
1                 Animal Crossing New Horizons Catalog   
2                          Credit Card Fraud Detection   
3                          Netflix Movies and TV Shows   
4                      Novel Corona Virus 2019 Dataset   
..                                                 ...   
994                      Economic Freedom of the World   
995                    Zillow Rent Index, 2010-Present   
996                   The Interview Attendance Problem   
997                          US Population By Zip Code   
998                           British Birdsong Dataset   

                       uploaded_by           last_updated  usability  \
0          Allen Institute For AI     Updated 12 days ago        8.8   
1                      Jessica Li    Updated 7 months ago        8.2   
2    Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                   Shivam Bansal    Updated 3 months ago       10.0   
4                             SRK    Updated 6 months ago        9.7   
..                             ...                    ...        ...   
994  Guillermina Sutter Schneider     Updated 3 years ago        7.4   
995                        Zillow     Updated 5 years ago        7.4   
996                VishnuRaghavan     Updated 4 years ago        7.9   
997              US Census Bureau     Updated 5 years ago        8.2   
998                Rachael Tatman     Updated 4 years ago        7.6   

                                 files     size  upvotes   badge  
0     558167 Files (JSON, CSV, other)     14 GB     9710    Gold  
1                      30 Files (CSV)    591 kB     9652    Gold  
2                        1 File (CSV)     69 MB     8712    Gold  
3                        1 File (CSV)      1 MB     6056    Gold  
4                       6 Files (CSV)      9 MB     5679    Gold  
..                                 ...      ...      ...     ...  
994                      1 File (CSV)    413 kB      114  Bronze  
995                     2 Files (CSV)      4 MB      114  Bronze  
996              2 Files (CSV, other)    127 kB      114  Silver  
997                     2 Files (CSV)     30 MB      114  Silver  
998            264 Files (other, CSV)    664 MB      115  Silver  

[999 rows x 8 columns]

# **EDA**

In [96]:
df.shape

(999, 8)

In [97]:
df.head()

title  \
0  COVID-19 Open Research Dataset Challenge (CORD...   
1               Animal Crossing New Horizons Catalog   
2                        Credit Card Fraud Detection   
3                        Netflix Movies and TV Shows   
4                    Novel Corona Virus 2019 Dataset   

                     uploaded_by           last_updated  usability  \
0        Allen Institute For AI     Updated 12 days ago        8.8   
1                    Jessica Li    Updated 7 months ago        8.2   
2  Machine Learning Group - ULB     Updated 4 years ago        8.5   
3                 Shivam Bansal    Updated 3 months ago       10.0   
4                           SRK    Updated 6 months ago        9.7   

                               files     size  upvotes badge  
0   558167 Files (JSON, CSV, other)     14 GB     9710  Gold  
1                    30 Files (CSV)    591 kB     9652  Gold  
2                      1 File (CSV)     69 MB     8712  Gold  
3                      1 File (CSV)      1 MB     6056  Gold  
4                     6 Files (CSV)      9 MB     5679  Gold

In [98]:
df.tail()

title                    uploaded_by  \
994     Economic Freedom of the World  Guillermina Sutter Schneider    
995   Zillow Rent Index, 2010-Present                        Zillow    
996  The Interview Attendance Problem                VishnuRaghavan    
997         US Population By Zip Code              US Census Bureau    
998          British Birdsong Dataset                Rachael Tatman    

             last_updated  usability                     files     size  \
994   Updated 3 years ago        7.4             1 File (CSV)    413 kB   
995   Updated 5 years ago        7.4            2 Files (CSV)      4 MB   
996   Updated 4 years ago        7.9     2 Files (CSV, other)    127 kB   
997   Updated 5 years ago        8.2            2 Files (CSV)     30 MB   
998   Updated 4 years ago        7.6   264 Files (other, CSV)    664 MB   

     upvotes   badge  
994      114  Bronze  
995      114  Bronze  
996      114  Silver  
997      114  Silver  
998      115  Silver

In [99]:
df.iloc[21:25]

title            uploaded_by  \
21            Suicide Rates Overview 1985 to 2016                 Rusty    
22                                 Avocado Prices        Justin Kiggins    
23                             The Movies Dataset          Rounak Banik    
24  Breast Cancer Wisconsin (Diagnostic) Data Set  UCI Machine Learning    

            last_updated  usability            files     size  upvotes badge  
21   Updated 3 years ago        8.2    1 File (CSV)    407 kB     2760  Gold  
22   Updated 4 years ago        9.7    1 File (CSV)    644 kB     2711  Gold  
23   Updated 4 years ago        8.2   7 Files (CSV)    239 MB     2698  Gold  
24   Updated 5 years ago        8.5    1 File (CSV)     50 kB     2511  Gold

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   title         999 non-null    object 
 1   uploaded_by   999 non-null    object 
 2   last_updated  999 non-null    object 
 3   usability     999 non-null    float64
 4   files         999 non-null    object 
 5   size          999 non-null    object 
 6   upvotes       999 non-null    int64  
 7   badge         999 non-null    object 
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB


In [101]:
df.describe()

usability      upvotes
count  999.000000   999.000000
mean     8.123924   457.679680
std      1.622493   789.305502
min      1.200000   114.000000
25%      7.100000   151.000000
50%      8.200000   221.000000
75%      9.700000   416.000000
max     10.000000  9710.000000

In [102]:
df.isnull()

title  uploaded_by  last_updated  usability  files   size  upvotes  badge
0    False        False         False      False  False  False    False  False
1    False        False         False      False  False  False    False  False
2    False        False         False      False  False  False    False  False
3    False        False         False      False  False  False    False  False
4    False        False         False      False  False  False    False  False
..     ...          ...           ...        ...    ...    ...      ...    ...
994  False        False         False      False  False  False    False  False
995  False        False         False      False  False  False    False  False
996  False        False         False      False  False  False    False  False
997  False        False         False      False  False  False    False  False
998  False        False         False      False  False  False    False  False

[999 rows x 8 columns]

In [103]:
df.isnull().sum()

title           0
uploaded_by     0
last_updated    0
usability       0
files           0
size            0
upvotes         0
badge           0
dtype: int64

# LabelEncoder

In [104]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['title'] = label_encoder.fit_transform(df['title'])
df['uploaded_by'] = label_encoder.fit_transform(df['uploaded_by'])
df['last_updated'] = label_encoder.fit_transform(df['last_updated'])
df['usability'] = label_encoder.fit_transform(df['usability'])
df['files'] = label_encoder.fit_transform(df['files'])
df['size'] = label_encoder.fit_transform(df['size'])
df['upvotes'] = label_encoder.fit_transform(df['upvotes'])
df['badge'] = label_encoder.fit_transform(df['badge'])

# SEPARATING DATASET

In [105]:
df1 = df.iloc[0:340]

In [106]:
df1

title  uploaded_by  last_updated  usability  files  size  upvotes  badge
0      160           35             1         27    227    54      472      1
1       75          273            27         25    147   331      471      1
2      244          334            19         26      0   365      470      1
3      633          528            16         31      0     1      469      1
4      646          499            24         30    233   442      468      1
..     ...          ...           ...        ...    ...   ...      ...    ...
335    898           19            32         30      0    41      192      1
336    518          569            32         29      0   178      192      1
337    791          416            17         28    233   213      191      2
338    141          674             7         16    138   336      191      1
339    831          642            19         22    112     4      190      1

[340 rows x 8 columns]

In [107]:
df2 = df.iloc[341:671]

In [108]:
df2

title  uploaded_by  last_updated  usability  files  size  upvotes  badge
341    532          467            19         27    289   178      189      1
342    105          630             7         31     67     1      189      1
343    174          585            32         31      0    40      189      1
344    817          492            21         31      0    10      188      1
345    963          600            22         25     80   106      187      2
..     ...          ...           ...        ...    ...   ...      ...    ...
666    743          676            19          5      0   218       54      2
667    262          408            32         31    187   178       54      1
668    733          160             7         31     80    16       54      2
669    692          293            19         15     74   232       54      2
670    984          419            16         27    173    65       56      1

[330 rows x 8 columns]

In [109]:
df3 = df.iloc[671:1000]

In [110]:
df3

title  uploaded_by  last_updated  usability  files  size  upvotes  badge
671    286          367            32         31      0   443       57      1
672    680          281            32         30    209     4       54      1
673    425          218            17         19    298   465       53      2
674    207          203            29         29     52    79       53      1
675    951          695            27         25      2   295       54      2
..     ...          ...           ...        ...    ...   ...      ...    ...
994    313          222            17         20      0   245        0      0
995    960          646            22         20     80   233        0      0
996    833          618            19         23     82    39        0      2
997    899          601            22         25     80   180        0      2
998    146          467            19         22    128   359        1      2

[328 rows x 8 columns]

In [111]:
x = df1.iloc[:, :-1]
y = df1.iloc[:, -1]

In [112]:
x

title  uploaded_by  last_updated  usability  files  size  upvotes
0      160           35             1         27    227    54      472
1       75          273            27         25    147   331      471
2      244          334            19         26      0   365      470
3      633          528            16         31      0     1      469
4      646          499            24         30    233   442      468
..     ...          ...           ...        ...    ...   ...      ...
335    898           19            32         30      0    41      192
336    518          569            32         29      0   178      192
337    791          416            17         28    233   213      191
338    141          674             7         16    138   336      191
339    831          642            19         22    112     4      190

[340 rows x 7 columns]

In [113]:
y

0      1
1      1
2      1
3      1
4      1
      ..
335    1
336    1
337    2
338    1
339    1
Name: badge, Length: 340, dtype: int64

# Train Test Split

In [114]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 10)

In [115]:
y_test

322    2
227    1
323    2
113    1
80     1
      ..
121    1
312    1
181    1
274    1
174    1
Name: badge, Length: 85, dtype: int64

# DECISION TREES

In [116]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier(random_state=1234)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(random_state=1234)

In [117]:
y_predict = dtc.predict(x_test)

In [118]:
y_predict

array([2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1])

# confusion_matrix

In [119]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict)
score = dtc.score(x_test, y_test)


In [120]:
cm

array([[77,  3],
       [ 3,  2]])

In [121]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_predict)
print('Accuracy',accuracy)
recall = recall_score(y_test,y_predict,average = 'macro')
print('Recall',recall)
f1score = f1_score(y_test, y_predict,average = 'macro')
print('f1 score',f1score)

Accuracy 0.9294117647058824
Recall 0.68125
f1 score 0.6812500000000001


# LOGISTIC REGRESSION

In [122]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [123]:
from sklearn.linear_model import LogisticRegression
logistic_classifier = LogisticRegression()
logistic_classifier.fit(x_train,y_train)


LogisticRegression()

In [124]:
y_predict1 = logistic_classifier.predict(x_test)

In [125]:
y_predict1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1])

# confusion_matrix

In [126]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict1)
score = dtc.score(x_test, y_test)

In [127]:
cm

array([[ 0,  1,  1],
       [ 0, 58,  3],
       [ 0,  4,  1]])

In [128]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_predict1)
print('Accuracy',accuracy)
recall = recall_score(y_test,y_predict1,average = 'macro')
print('Recall',recall)
f1score = f1_score(y_test, y_predict1,average = 'macro')
print('f1 score',f1score)

Accuracy 0.8676470588235294
Recall 0.38360655737704913
f1 score 0.3784946236559139


# AdaBoostClassifier

In [129]:
from sklearn.ensemble import AdaBoostClassifier

In [130]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [131]:
abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
model = abc.fit(x_train, y_train)

In [132]:
y_predict2 = model.predict(x_test)

In [133]:
y_predict2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# confusion_matrix

In [134]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict2)
score = dtc.score(x_test, y_test)

In [135]:
cm

array([[92,  3],
       [ 6,  1]])

In [136]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_predict2)
print('Accuracy',accuracy)
recall = recall_score(y_test,y_predict2,average = 'macro')
print('Recall',recall)
f1score = f1_score(y_test, y_predict2,average = 'macro')
print('f1 score',f1score)

Accuracy 0.9117647058823529
Recall 0.5556390977443609
f1 score 0.5675930287329252


# KNN

In [137]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.30, random_state=0)

In [138]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5,p=2 )

In [139]:
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [140]:
y_predict3 = classifier.predict(x_test)

In [141]:
y_predict3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# confusion_matrix

In [142]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict3)
score = dtc.score(x_test, y_test)

In [143]:
cm

array([[ 0,  1,  0],
       [ 0, 95,  0],
       [ 0,  6,  0]])

In [144]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_predict3)
print('Accuracy',accuracy)
recall = recall_score(y_test,y_predict3,average = 'macro')
print('Recall',recall)
f1score = f1_score(y_test, y_predict3,average = 'macro')
print('f1 score',f1score)

Accuracy 0.9313725490196079
Recall 0.3333333333333333
f1 score 0.32148900169204736


# SVM

In [145]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 1234, stratify=y)

In [146]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)

SVC()

In [147]:
y_predict4 = svc.predict(x_test)

In [148]:
y_predict4

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Confusion_matrix

In [149]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_predict4)

In [150]:
cm

array([[ 0,  1,  0],
       [ 0, 94,  0],
       [ 0,  7,  0]])

In [151]:
from sklearn.metrics import accuracy_score,recall_score,f1_score
accuracy = accuracy_score(y_test, y_predict4)
print('Accuracy',accuracy)
recall = recall_score(y_test,y_predict4,average = 'macro')
print('Recall',recall)
f1score = f1_score(y_test, y_predict4,average = 'macro')
print('f1 score',f1score)

Accuracy 0.9215686274509803
Recall 0.3333333333333333
f1 score 0.3197278911564626
